### ISSUE TITLE
Comments-S

### ISSUE THREAD

**Issue by polarstern** [QuantLet/QID-1482-MVAtdistail#4]
Description: should begin with capital letter
 Author: the name should be written exactly as on the website
 Example: should contain some new information and not simply repeat info from description/input/output, otherwise should be deleted
 See also: Could add this info (and maybe new keywords) later after validation of other q's. Every status "Validated by..." means "first validation". Final validation will be only after we'll validate all q's which are now at github and correct something for having the same style (if needed).

**Comment by Tdannen** [comment]
understood
